/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __ASM_LITTLE64_SPECIAL_REGISTERS_H
#define __ASM_LITTLE64_SPECIAL_REGISTERS_H

#define LITTLE64_SR_CPU_CONTROL               0

#define LITTLE64_SR_SELECTOR_MASK         0xFFFF
#define LITTLE64_SR_USER_BANK_BIT         0x8000
#define LITTLE64_SR_USER_THREAD_POINTER   (LITTLE64_SR_USER_BANK_BIT | 0)

#define LITTLE64_SR_PAGE_TABLE_ROOT_PHYSICAL 11
#define LITTLE64_SR_BOOT_INFO_FRAME_PHYSICAL 12
#define LITTLE64_SR_BOOT_SOURCE_PAGE_SIZE    13
#define LITTLE64_SR_BOOT_SOURCE_PAGE_COUNT   14
#define LITTLE64_SR_HYPERCALL_CAPS           15

#define LITTLE64_SR_INTERRUPT_TABLE_BASE     16
#define LITTLE64_SR_INTERRUPT_MASK           17
#define LITTLE64_SR_INTERRUPT_MASK_HIGH      18
#define LITTLE64_SR_INTERRUPT_STATES         19
#define LITTLE64_SR_INTERRUPT_STATES_HIGH    20
#define LITTLE64_SR_INTERRUPT_EPC            21
#define LITTLE64_SR_INTERRUPT_EFLAGS         22
#define LITTLE64_SR_INTERRUPT_CPU_CONTROL    23
#define LITTLE64_SR_TRAP_CAUSE               24
#define LITTLE64_SR_TRAP_FAULT_ADDR          25
#define LITTLE64_SR_TRAP_ACCESS              26
#define LITTLE64_SR_TRAP_PC                  27
#define LITTLE64_SR_TRAP_AUX                 28

#endif /* __ASM_LITTLE64_SPECIAL_REGISTERS_H */